services:
  typescript:
    build:
      context: . 
      dockerfile: ./typescript/Dockerfile
      args:
        USERNAME: "${LOCAL_USERNAME:-vscode}"
        USER_UID: "${LOCAL_USER_UID:-1000}"
        USER_GID: "${LOCAL_USER_GID:-1000}"
    volumes:
      # Mount to a fixed path instead of a username-dependent path
      - ../typescript-workspace:/workspace:cached
    # Use a fixed working directory
    working_dir: /workspace
    command: sleep infinity

  python:
    build: 
      context: . 
      dockerfile: ./python/Dockerfile
      args:
        USERNAME: "${LOCAL_USERNAME:-vscode}"
        USER_UID: "${LOCAL_USER_UID:-1000}"
        USER_GID: "${LOCAL_USER_GID:-1000}"
    volumes:
      # Mount to a fixed path instead of a username-dependent path
      - ../python-workspace:/workspace:cached
    # Use a fixed working directory
    working_dir: /workspace
    network_mode: "host"
    command: sleep infinity

  texlive:
    build:
      context: . 
      dockerfile: ./texlive/Dockerfile
      args:
        USERNAME: "${LOCAL_USERNAME:-vscode}"
        USER_UID: "${LOCAL_USER_UID:-1000}"
        USER_GID: "${LOCAL_USER_GID:-1000}"
    volumes:
      # Mount to a fixed path instead of a username-dependent path
      - ../texlive-workspace:/workspace:cached
    # Use a fixed working directory
    working_dir: /workspace
    command: sleep infinity