services:
  typescript:
    build:
      context: . 
      dockerfile: ./typescript/Dockerfile
      args:
        USERNAME: "${LOCAL_USERNAME:-vscode}"
        USER_UID: "${LOCAL_USER_UID:-1000}"
        USER_GID: "${LOCAL_USER_GID:-1000}"
    volumes:
      - .:/workspace:cached
    working_dir: /workspace/typescript-workspace
    command: sleep infinity

  python:
    build: 
      context: . 
      dockerfile: ./python/Dockerfile
      args:
        USERNAME: "${LOCAL_USERNAME:-vscode}"
        USER_UID: "${LOCAL_USER_UID:-1000}"
        USER_GID: "${LOCAL_USER_GID:-1000}"
    volumes:
      - .:/workspace:cached
    working_dir: /workspace/python-workspace
    network_mode: "host"
    command: sleep infinity

  texlive:
    build:
      context: . 
      dockerfile: ./texlive/Dockerfile
      args:
        USERNAME: "${LOCAL_USERNAME:-vscode}"
        USER_UID: "${LOCAL_USER_UID:-1000}"
        USER_GID: "${LOCAL_USER_GID:-1000}"
    volumes:
      - .:/workspace:cached
    working_dir: /workspace/texlive-workspace
    command: sleep infinity